# Generated by Django 5.2.9 on 2026-01-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content1', models.TextField(blank=True)),
                ('content2', models.TextField(blank=True)),
                ('content3', models.TextField(blank=True)),
                ('content4', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
