# Generated by Django 5.2.9 on 2026-01-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themeOne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='css_file',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
