# Generated by Django 5.2.11 on 2026-03-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themeOne', '0002_page_css_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='grid_layout',
            field=models.CharField(choices=[('1col', '1 Column'), ('2col', '2 Columns'), ('3col', '3 Columns'), ('4col', '4 Columns')], default='2col', max_length=10),
        ),
    ]
