# Generated by Django 5.2.11 on 2026-03-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themeOne', '0003_page_grid_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='grid_layout',
            field=models.CharField(choices=[('col-1', '1 Column'), ('col-2', '2 Columns'), ('col-3', '3 Columns'), ('col-4', '4 Columns')], default='2col', max_length=10),
        ),
    ]
