# Generated by Django 5.2.11 on 2026-03-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themeOne', '0004_alter_page_grid_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content8',
            field=models.TextField(blank=True),
        ),
    ]
