# Generated by Django 5.2.12 on 2026-03-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themeOne', '0005_page_content5_page_content6_page_content7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content12',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content13',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content14',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content15',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content16',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content9',
            field=models.TextField(blank=True),
        ),
    ]
