# Generated by Django 5.2.12 on 2026-03-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themeOne', '0006_page_content10_page_content11_page_content12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content17',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content18',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content19',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content20',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content21',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content22',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content23',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content24',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content25',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content26',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content27',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content28',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content29',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content30',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content31',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content32',
            field=models.TextField(blank=True),
        ),
    ]
