# Generated by Django 5.2.13 on 2026-05-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themeOne', '0007_page_content17_page_content18_page_content19_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
