# Generated by Django 5.2.13 on 2026-05-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themeOne', '0008_navbaritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
